name: Push to Development

on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm run

      - name: Build 
        run: npm export

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: swenewsapp.com
          username: ${{ secrets.FTP_PROD_USER }}
          password: ${{ secrets.FTP_PROD_PASS }}
          server-dir: /home/swen-prod/web/app.swenewsapp.com/public_html/
          port: ${{ secrets.FTP_PROD_PORT }}